In [2]:
import torch

In [4]:
torch.cuda.is_available()

False

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [17]:
x = [[i for i in range(3)] for _ in range(3)]
x = torch.tensor(x, dtype=torch.float32, device=device)
x

tensor([[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]])

In [11]:
y = torch.rand((3,3))
y

tensor([[0.3678, 0.6828, 0.7618],
        [0.3746, 0.3905, 0.4838],
        [0.8306, 0.0025, 0.7007]])

In [14]:
z = torch.empty((3,3), device=device)
z

tensor([[1.6816e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [18]:
x.requires_grad_()
f = x.pow(2).sum()
f.backward()

In [20]:
x.grad

tensor([[0., 2., 4.],
        [0., 2., 4.],
        [0., 2., 4.]])

In [22]:
from torch.utils.data import Dataset, DataLoader
import pandas as pd

In [23]:
data = pd.DataFrame({"x": [5 + i/10 for i in range(20)], "y": [i//10 for i in range(20)]})
data

x  y
0   5.0  0
1   5.1  0
2   5.2  0
3   5.3  0
4   5.4  0
5   5.5  0
6   5.6  0
7   5.7  0
8   5.8  0
9   5.9  0
10  6.0  1
11  6.1  1
12  6.2  1
13  6.3  1
14  6.4  1
15  6.5  1
16  6.6  1
17  6.7  1
18  6.8  1
19  6.9  1

In [53]:
class MyDataset(Dataset):
    def __init__(self, dataframe: pd.DataFrame) -> None:
        self.data = dataframe
    
    def __len__(self) -> int:
        return len(self.data)
    
    def __getitem__(self, idx):
        return self.data.iloc[idx].values

In [54]:
dataset = MyDataset(data)

In [55]:
train, val, test = torch.utils.data.random_split(dataset, [15, 3, 2])

In [56]:
data_tensor = torch.tensor(data.values, requires_grad=True)

In [57]:
train_loader = DataLoader(train, batch_size=5, shuffle=True)

In [58]:
train_loader

In [59]:
next(iter(train_loader))

tensor([[5.7000, 0.0000],
        [5.8000, 0.0000],
        [6.7000, 1.0000],
        [5.6000, 0.0000],
        [6.8000, 1.0000]], dtype=torch.float64)

In [60]:
val_loader = DataLoader(val)
test_loader = DataLoader(test)

In [61]:
import torch.nn as nn
import torch.nn.functional as F

In [64]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(1, 1)
        self.fc2 = nn.Linear(1, 1)
    
    def forward(self, x: torch.Tensor):
        x = F.relu(self.fc1(x))
        x = F.softmax(self.fc2(x))
        
        return x
        

In [65]:
simple_nn = SimpleNN()
simple_nn

SimpleNN(
  (fc1): Linear(in_features=1, out_features=1, bias=True)
  (fc2): Linear(in_features=1, out_features=1, bias=True)
)